// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/siyajj-hero/HeroEditorial.tsx": () => import("../components/mockups/siyajj-hero/HeroEditorial.tsx"),
  "./components/mockups/siyajj-hero/HeroGeometric.tsx": () => import("../components/mockups/siyajj-hero/HeroGeometric.tsx"),
  "./components/mockups/siyajj-hero/HeroSplit.tsx": () => import("../components/mockups/siyajj-hero/HeroSplit.tsx")
};
